default: &default
  host: db
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1
  socket: '/var/run/mysqld/mysqld.sock'

development:
  <<: *default
  database: rails_docker_app_development
test:
  <<: *default
  database: rails_docker_app_test

production:
  <<: *default
  database: rails_docker_app_production
  username: rails_docker_app
  password: <%= ENV['RAILS_DOCKER_APP_DATABASE_PASSWORD'] %>
